version: '3'
services:
  node-app:
    container_name: node-app
    build:
      context: ./mapdraw/server/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '3000:3000' # Port for React development server
    volumes:
      - ./mapdraw/:/usr/src/app
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    build:
      context: ./mapdraw/scripts/
      dockerfile: DockerFile
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./mapdraw/:/usr/src/app
volumes:
  mongo_data:
